### ISSUE TITLE
libpappl writes TLS certificates into hard-coded /etc/cups/ssl/ directory

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#144]
I want to snap the PostScript Printer Application in a way that after installing the Snap the server gets automatically started. For this I create an app with `daemon: simple` in `snapcraft.yaml`:
```
apps:
  ps-printer-app-server:
    command: scripts/run-ps-printer-app -o log-level=debug -o log-file=/var/snap/ps-printer-app/common/ps-printer-app.log server
    daemon: simple
    plugs: [avahi-control, home, log-observe, network, network-bind, network-manager, raw-usb]
  ps-printer-app:
    command: scripts/run-ps-printer-app
    plugs: [avahi-control, home, log-observe, network, network-bind, network-manager, raw-usb]
```
The `scripts/run-ps-printer-app` sets some environment variables to tell the Printer Application where to put its files and then starts `ps-printer-app` itself, passing through all command line arguments.

This makes the server instance of the Printer Application running as root, and the TLS functions in `pappl/system-webif.c` try to put the certificates into `/etc/cups/ssl/` which is not accessible in the Snap. The Snap would need its own place (usually somewhere in `/var/snap/ps-printer-app/current/`).

There is no way to change this at build time via `./configure` option nor at run time by an environment variable or command line option.
